package com.vaibhav.moneycapture

import android.app.Notification
import android.content.Context
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import java.util.Locale
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.Executors
import java.util.regex.Pattern

class MoneyNotificationListener : NotificationListenerService() {

    private val executor = Executors.newSingleThreadExecutor()

    /*
     * Stores recently captured transaction fingerprints.
     *
     * The important difference from the old version is that we do NOT use
     * notification ID + post time as the duplicate key.
     *
     * Banks can send multiple notifications for the same transaction.
     */
    private val seenTransactions = ConcurrentHashMap<String, Long>()

    override fun onNotificationPosted(sbn: StatusBarNotification) {

        val n = sbn.notification ?: return

        val extras = n.extras ?: return

        val title =
            extras.getCharSequence(Notification.EXTRA_TITLE)
                ?.toString()
                .orEmpty()

        val textLines = buildList {

            append(
                extras.getCharSequence(Notification.EXTRA_TEXT)
                    ?.toString()
                    .orEmpty()
            )

            append(
                extras.getCharSequence(Notification.EXTRA_BIG_TEXT)
                    ?.toString()
                    .orEmpty()
            )

            val lines =
                extras.getCharSequenceArray(Notification.EXTRA_TEXT_LINES)

            if (lines != null) {
                append(
                    lines.joinToString(" ") {
                        it.toString()
                    }
                )
            }
        }
            .filter {
                it.isNotBlank()
            }
            .joinToString(" ")
            .trim()

        val bigText =
            extras.getCharSequence(Notification.EXTRA_BIG_TEXT)
                ?.toString()
                .orEmpty()

        if (bigText.isNotBlank()) {
            // Keep big text available in the combined notification text.
        }

        if (title.isBlank() && text.isBlank()) {
            return
        }

        /*
         * Ignore notifications that don't look like transactions.
         */
        if (!looksLikeTransaction(title, text)) {
            return
        }

        /*
         * Create a transaction fingerprint that does NOT depend on
         * notification ID or notification post time.
         *
         * This is what prevents Kotak's duplicate notifications.
         */
        val transactionKey =
            createTransactionKey(
                packageName = sbn.packageName,
                title = title,
                text = text
            )

        /*
         * Keep only a bounded in-memory cache.
         *
         * 2 minutes is long enough for two notifications belonging to
         * the same transaction to arrive close together.
         */
        val now = System.currentTimeMillis()
        val cutoff = now - (2 * 60 * 1000L)

        seenTransactions.entries.removeIf {
            it.value < cutoff
        }

        /*
         * If this exact transaction was already processed recently,
         * ignore the notification.
         */
        val previous = seenTransactions.putIfAbsent(
            transactionKey,
            now
        )

        if (previous != null) {
            return
        }

        /*
         * Read endpoint and secret from app settings.
         */
        val prefs =
            getSharedPreferences(
                "capture",
                Context.MODE_PRIVATE
            )

        val endpoint =
            prefs.getString("endpoint", "").orEmpty()

        val secret =
            prefs.getString("secret", "").orEmpty()

        if (endpoint.isBlank() || secret.isBlank()) {
            return
        }

        /*
         * Send the transaction to Google Apps Script.
         */
        executor.execute {

            NotificationPoster.post(
                context = this,
                endpoint = endpoint,
                secret = secret,
                payload = TransactionPayload(
                    packageName = sbn.packageName,
                    appName =
                        title.ifBlank {
                            sbn.packageName
                        },
                    title = title,
                    text = text,
                    postedAt = sbn.postTime,
                    notificationKey = transactionKey
                )
            )
        }
    }

    /*
     * Creates a stable fingerprint for a transaction.
     *
     * We intentionally remove:
     * - notification IDs
     * - timestamps
     * - changing balance numbers
     * - reference numbers
     *
     * so two notifications generated by the bank for the same payment
     * are much more likely to produce the same key.
     */
    private fun createTransactionKey(
        packageName: String,
        title: String,
        text: String
    ): String {

        val combined =
            "$title $text"
                .lowercase(Locale.ROOT)
                .replace(Regex("\\s+"), " ")
                .trim()

        val amount =
            extractAmount(combined)

        val direction =
            when {
                containsAny(
                    combined,
                    listOf(
                        "credited",
                        "received",
                        "received rs",
                        "money received",
                        "payment received",
                        "credit"
                    )
                ) -> "credit"

                containsAny(
                    combined,
                    listOf(
                        "debited",
                        "sent",
                        "paid",
                        "payment made",
                        "money sent",
                        "debit"
                    )
                ) -> "debit"

                else -> "unknown"
            }

        /*
         * Remove numbers that commonly change between duplicate
         * notifications, such as:
         *
         * - balance
         * - transaction reference
         * - UTR
         * - dates/times
         *
         * Keep the textual transaction information.
         */
        val normalizedText =
            combined
                .replace(
                    Regex(
                        "(?i)(utr|ref(?:erence)?|txn|transaction\\s*(?:id|no|number)?)[\\s:#-]*[a-z0-9-]+"
                    ),
                    ""
                )
                .replace(
                    Regex(
                        "(?i)(balance|bal|avl|available)\\s*(?:is|:)?\\s*(?:rs\\.?|₹)?\\s*[0-9,]+(?:\\.\\d{1,2})?"
                    ),
                    ""
                )
                .replace(
                    Regex(
                        "\\b\\d{1,2}[:/]\\d{1,2}(?::\\d{1,2})?\\b"
                    ),
                    ""
                )
                .replace(
                    Regex(
                        "\\b\\d{4,}\\b"
                    ),
                    ""
                )
                .replace(
                    Regex("\\s+"),
                    " "
                )
                .trim()

        return buildString {

            append(packageName)
            append("|")
            append(direction)
            append("|")
            append(amount ?: "no_amount")
            append("|")
            append(
                normalizedText
            )

        }
    }

    private fun extractAmount(
        text: String
    ): String? {

        /*
         * Supports examples such as:
         *
         * ₹10
         * Rs 10
         * Rs. 10
         * INR 10
         * INR10
         * ₹1,250.50
         */
        val pattern =
            Pattern.compile(
                "(?:₹|rs\\.?|inr)\\s*([0-9,]+(?:\\.\\d{1,2})?)",
                Pattern.CASE_INSENSITIVE
            )

        val matcher =
            pattern.matcher(text)

        if (matcher.find()) {

            return matcher.group(1)
                ?.replace(",", "")
        }

        return null
    }

    private fun containsAny(
        text: String,
        words: List<String>
    ): Boolean {

        return words.any {
            text.contains(it)
        }
    }

    private fun looksLikeTransaction(
        title: String,
        text: String
    ): Boolean {

        val s =
            "$title $text"
                .lowercase(Locale.ROOT)

        val amountPattern =
            Pattern.compile(
                "(?:₹|rs\\.?|inr)\\s*[0-9,]+(?:\\.\\d{1,2})?",
                Pattern.CASE_INSENSITIVE
            )

        val amountFound =
            amountPattern
                .matcher(s)
                .find()

        if (!amountFound) {
            return false
        }

        val keywords =
            listOf(
                "debit",
                "debited",
                "credit",
                "credited",
                "received",
                "sent",
                "paid",
                "payment",
                "transaction",
                "txn",
                "upi",
                "bank",
                "transfer",
                "a/c",
                "account"
            )

        return keywords.any {
            s.contains(it)
        }
    }
}

